- become: yes
  hosts: all
  name: Setup and
  tasks:
    - name: Update Yum
      yum:
        name: '*'
        state: latest
        update_cache: yes
      register: yum_update
    - name: Install Docker
      yum:
        name: docker
        state: present
      register: docker_install
    - name: Start Docker
      service:
        name: docker
        state: started
      register: docker_start
    - name: Add User to Docker Group
      user:
        name: ec2-user
        groups: docker
        append: yes
      register: docker_user
    - name: Install Python Docker
      pip:
        name: docker
        state: present
    - name: Get ECR Login
      shell: aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com
      register: ecr_login
    - name: Pull Estuary from ECR
      community.docker.docker_image:
        name: "public.ecr.aws/jg/hello:latest"
        source: pull
    - name: Run App Container
      docker_container:
        name: estuary
        image: "public.ecr.aws/jg/hello:latest"
        state: started
        restart_policy: always
        ports:
          - "80:80"
        command: [ ]
      register: "app_container_run"

